language: C

branches:
  except:
    - master

git:
  depth: false

notifications:
  irc:
    channels:
      - "ircs://chat.freenode.net:6697/#libxcrypt"
    skip_join: true

dist: trusty
sudo: required

matrix:
  fast_finish: true
  include:
    - name: "Coverity Scan"
      if: tag =~ ^v(\d+\.)?(\d+\.)?(\d+)$
      compiler: gcc
      os: linux
      env:
        - CONF="--disable-werror --enable-obsolete-api --enable-hashes=all"
        - PERFORM_COVERITY_SCAN="1"
        - COVERITY_SCAN_PROJECT_NAME="$TRAVIS_REPO_SLUG"
        - COVERITY_SCAN_BRANCH_PATTERN="^v(\d+\.)?(\d+\.)?(\d+)$"
        - COVERITY_SCAN_BUILD_COMMAND_PREPEND="./bootstrap && ./configure $CONF"
        - COVERITY_SCAN_BUILD_COMMAND="make -j$NPROCS"
    - name: "Fedora Rawhide, GCC, Codecov"
      compiler: gcc
      os: linux
      services: docker
      env:
        - CONF="--enable-obsolete-api --enable-hashes=all"
        - FCVER="rawhide"
        - CODECOV=1
    - name: "Fedora Rawhide, GCC, all hashes, obsolete API"
      compiler: gcc
      os: linux
      services: docker
      env:
        - CONF="--enable-obsolete-api --enable-hashes=all"
        - FCVER="rawhide"
        - DISTCHECK=1
    - name: "Fedora Rawhide, Clang, all hashes, obsolete API"
      compiler: clang
      os: linux
      services: docker
      env:
        - CONF="--enable-obsolete-api --enable-hashes=all"
        - FCVER="rawhide"
    - name: "Fedora stable, GCC, all hashes, obsolete API"
      compiler: gcc
      os: linux
      services: docker
      env:
        - CONF="--enable-obsolete-api --enable-hashes=all"
        - FCVER="latest"
    - name: "Fedora stable, Clang, all hashes, obsolete API"
      compiler: clang
      os: linux
      services: docker
      env:
        - CONF="--enable-obsolete-api --enable-hashes=all"
        - FCVER="latest"
    - name: "Fedora Rawhide, GCC, all hashes, obsolete API, no failure-tokens"
      compiler: gcc
      os: linux
      services: docker
      env:
        - CONF="--disable-failure-tokens --enable-obsolete-api --enable-hashes=all"
        - FCVER="rawhide"
    - name: "Fedora Rawhide, Clang, all hashes, obsolete API, no failure-tokens"
      compiler: clang
      os: linux
      services: docker
      env:
        - CONF="--disable-failure-tokens --enable-obsolete-api --enable-hashes=all"
        - FCVER="rawhide"
    - name: "Fedora stable, GCC, all hashes, obsolete API, no failure-tokens"
      compiler: gcc
      os: linux
      services: docker
      env:
        - CONF="--disable-failure-tokens --enable-obsolete-api --enable-hashes=all"
        - FCVER="latest"
    - name: "Fedora stable, Clang, all hashes, obsolete API, no failure-tokens"
      compiler: clang
      os: linux
      services: docker
      env:
        - CONF="--disable-failure-tokens --enable-obsolete-api --enable-hashes=all"
        - FCVER="latest"
    - name: "Fedora Rawhide, GCC, all hashes, no obsolete API"
      compiler: gcc
      os: linux
      services: docker
      env:
        - CONF="--disable-obsolete-api --enable-hashes=all"
        - FCVER="rawhide"
    - name: "Fedora Rawhide, Clang, all hashes, no obsolete API"
      compiler: clang
      os: linux
      services: docker
      env:
        - CONF="--disable-obsolete-api --enable-hashes=all"
        - FCVER="rawhide"
    - name: "Fedora stable, GCC, all hashes, no obsolete API"
      compiler: gcc
      os: linux
      services: docker
      env:
        - CONF="--disable-obsolete-api --enable-hashes=all"
        - FCVER="latest"
    - name: "Fedora stable, Clang, all hashes, no obsolete API"
      compiler: clang
      os: linux
      services: docker
      env:
        - CONF="--disable-obsolete-api --enable-hashes=all"
        - FCVER="latest"
    - name: "Fedora Rawhide, GCC, strong hashes, no obsolete API"
      compiler: gcc
      os: linux
      services: docker
      env:
        - CONF="--disable-obsolete-api --enable-hashes=strong"
        - FCVER="rawhide"
    - name: "Fedora Rawhide, Clang, strong hashes, no obsolete API"
      compiler: clang
      os: linux
      services: docker
      env:
        - CONF="--disable-obsolete-api --enable-hashes=strong"
        - FCVER="rawhide"
    - name: "Fedora stable, GCC, strong hashes, no obsolete API"
      compiler: gcc
      os: linux
      services: docker
      env:
        - CONF="--disable-obsolete-api --enable-hashes=strong"
        - FCVER="latest"
    - name: "Fedora stable, Clang, strong hashes, no obsolete API"
      compiler: clang
      os: linux
      services: docker
      env:
        - CONF="--disable-obsolete-api --enable-hashes=strong"
        - FCVER="latest"
    - name: "Fedora Rawhide, GCC, glibc hashes, obsolete API"
      compiler: gcc
      os: linux
      services: docker
      env:
        - CONF="--enable-obsolete-api --enable-hashes=glibc"
        - FCVER="rawhide"
    - name: "Fedora Rawhide, Clang, glibc hashes, obsolete API"
      compiler: clang
      os: linux
      services: docker
      env:
        - CONF="--enable-obsolete-api --enable-hashes=glibc"
        - FCVER="rawhide"
    - name: "Fedora stable, GCC, glibc hashes, obsolete API"
      compiler: gcc
      os: linux
      services: docker
      env:
        - CONF="--enable-obsolete-api --enable-hashes=glibc"
        - FCVER="latest"
    - name: "Fedora stable, Clang, glibc hashes, obsolete API"
      compiler: clang
      os: linux
      services: docker
      env:
        - CONF="--enable-obsolete-api --enable-hashes=glibc"
        - FCVER="latest"
    - name: "Fedora Rawhide, GCC, glibc and strong hashes, obsolete API for glibc"
      compiler: gcc
      os: linux
      services: docker
      env:
        - CONF="--enable-obsolete-api=glibc --enable-hashes=strong,glibc"
        - FCVER="rawhide"
    - name: "Fedora Rawhide, Clang, glibc and strong hashes, obsolete API for glibc"
      compiler: clang
      os: linux
      services: docker
      env:
        - CONF="--enable-obsolete-api=glibc --enable-hashes=strong,glibc"
        - FCVER="rawhide"
    - name: "Fedora stable, GCC, glibc and strong hashes, obsolete API for glibc"
      compiler: gcc
      os: linux
      services: docker
      env:
        - CONF="--enable-obsolete-api=glibc --enable-hashes=strong,glibc"
        - FCVER="latest"
    - name: "Fedora stable, Clang, glibc and strong hashes, obsolete API for glibc"
      compiler: clang
      os: linux
      services: docker
      env:
        - CONF="--enable-obsolete-api=glibc --enable-hashes=strong,glibc"
        - FCVER="latest"

before_install:
  - ./.travis_before_install.sh

before_script:
  - ./.travis_before_script.sh

script:
  - ./.travis_script.sh

after_success:
  - ./.travis_after_success.sh
