#!/bin/sh
set -e

PACKAGE="$1"
FILES="$2"

[ "$PACKAGE" -a "$FILES" ] || exit 1

sed -e "s#@DIVERT_FILES@#$FILES#" \
  < debian/common.preinst > debian/$PACKAGE.preinst

sed -e "s#@DIVERT_FILES@#$FILES#" \
  < debian/common.postrm  > debian/$PACKAGE.postrm

